import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex items-center justify-between border-b w-full p-4 text-xl font-semibold">
      <div>Gallery</div>
      <div>Sign In</div>

    </nav>
  )
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en"> 
      <body className={`${GeistSans.variable} flex flex-col gap-4`}>
        <TopNav />
          {children}
      </body>
    </html>
  );
}
