import "~/styles/globals.css";
import "@uploadthing/react/styles.css"

import { ClerkProvider } from '@clerk/nextjs';
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";

import { Inter } from "next/font/google";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TopNav } from "./_components/topnav";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "~/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: "T3 Gallery - V01",
  description: "Generated by Rashmi",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal
}: Readonly<{ 
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}> 
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}/>
        <body className={`font-sans ${inter.variable}`}>
          <div className="grid h-screen grid-rows=[auto,1fr]">
          <TopNav />
          <main className="overflow-y-scroll">  {children}</main>
          </div>
          {modal}
          <div id="modal-root" />
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
