import "~/styles/globals.css";
import "@uploadthing/react/styles.css"

import { ClerkProvider } from '@clerk/nextjs';

import { Inter } from "next/font/google";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";
import { TopNav } from "./_components/topnav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by Rashmi",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}> 
        <body className={`${GeistSans.variable} flex flex-col gap-4`}>
          <TopNav />
            {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
